### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by krishnak** [marcidy/micropython-uasyncio-websockets#1]
Especially for implementing this - I am not sure whether this is a common software pattern in Python but as a newbie to Python from C/Java I find the asyncio tutorials bit lacking. If you can suggest a good reading material for Python in general it will be great.

```
async def serve(cb, host, port):

    async def _connect(reader, writer):
        await connect(reader, writer, cb)

    return await asyncio.start_server(_connect, host, port)
```

However I am finding a vague issue 

Your code works with this syntax

```
uasyncio.create_task(websocket_server(add_client))

loop = uasyncio.get_event_loop()
loop.run_forever()

```
However when I try it with the "recommended syntax"

```

async def main():
    await websocket_server(add_client)

uasyncio.run(main())
```
Could you correct my syntax?

**Comment by krishnak** [comment]
This also doesn't work

```
async def main():
    await uasyncio.create_task(websocket_server(add_client))

uasyncio.run(main())

```

**Comment by marcidy** [comment]
I will give you a better response in the morning,  but for now, please have
a look at
https://github.com/marcidy/micropython-uasyncio-webexample/blob/main/dev/apps/echoserver/main.py

I do need to write a simple example and documentation.

**Comment by krishnak** [comment]
Thank you for replying. I have figured it out, I need to add a uasyncio.sleep() in the main method like this
```
async def main():
     uasyncio.create_task(websocket_server(add_client))
     while True:
        await uasyncio.sleep(.3)

uasyncio.run(main())
```
